platform: linux

image_resource:
    type: docker-image
    source:
        repository: pivotalservices/pks-kubectl

inputs:
- name: articulate-helmchart
  path: code
- name: articulate-ci
  path: ci


run:
  path: ./ci/config/deploy-pks-app.sh

params:
  PKS_API: ((PKS_API))
  PKS_CLI_USERNAME: ((PKS_CLI_USERNAME))
  PKS_CLI_PASSWORD: ((PKS_CLI_PASSWORD))
  PKS_CLUSTER_NAME: ((PKS_CLUSTER_NAME))
  PKS_SKIP_TLS_VERIFY: true